### ISSUE TITLE
Trouble understanding the script

### ISSUE THREAD

**Issue by TheBricktop** [ababilinski/unity-gpu-texture-resize#1]
I don't really see why the rendertexture is used here, the data is blitted once from input Texture2d to the rendertexture it doesn't seem to be used anywhere later.
What purpose does the rt fullfill?

**Comment by ababilinski** [comment]
Hi @TheBricktop , good question! 

We use the [RenderTexture](https://docs.unity3d.com/ScriptReference/RenderTexture.html) to do the resizing and then call Texture2D.ReadPixels to copy the pixels:
[Unity Documentation](https://docs.unity3d.com/ScriptReference/Texture2D.ReadPixels.html)

### Here is an outline of the process:

1. `RenderTexture rt = RenderTexture.GetTemporary()` create a temporary render texture with the target size
2. `RenderTexture.active` set the active [RenderTexture](https://docs.unity3d.com/ScriptReference/RenderTexture.html) to the temporary texture so we can read from it
3.  `Graphics.Blit()` Copies source texture into destination render texture with a shader _(on the gpu)_ [more info](https://docs.unity3d.com/ScriptReference/Graphics.Blit.html)
4. `texture2D.Resize()` resize the texture to the target values _(this sets the pixel data as undefined)_ [more info](https://docs.unity3d.com/ScriptReference/Texture2D.Resize.html)
5. ` texture2D.ReadPixels()` reads the pixel values from the temporary [RenderTexture](https://docs.unity3d.com/ScriptReference/RenderTexture.html) onto the resized texture [more info](https://docs.unity3d.com/ScriptReference/Texture2D.ReadPixels.html)
6. ` texture2D.Apply()`  actually upload the changed pixels to the graphics card [more info](https://docs.unity3d.com/ScriptReference/Texture2D.Apply.html)

Let me know if that helps :)

**Comment by TheBricktop** [comment]
Ah the step 5 actually clarifies how the data flow works. 
I have another question, how one could pipe in webcamtexture to get resized frames for some processing?
Graphics.CopyTexture comes to mind but im worried about what platforms actually can use it.

**Comment by ababilinski** [comment]
you can use the method above to resize your texture before processing. I created the extension while playing around with  [Barracuda-PoseNet](https://github.com/dahburj/Barracuda-PoseNet) 

however, I would recommend looking at [NNCam](https://github.com/keijiro/NNCam) since it uses the new PoseNet/BodyPix model along with some helpful compute shaders.
